#manifest:
#  remotes:
#    - name: zmkfirmware
#      url-base: https://github.com/infused-kim/zmk/tree/my-changes/oled-ext-pwr
#  projects:
#    - name: zmk
#remote: zmkfirmware
#      revision: main
#      import: app/west.yml
#  self:
#    path: config

#manifest:
#  remotes:
#    - name: infused-kim
#      url-base: https://github.com/infused-kim
#  projects:
#    - name: zmk
#     remote: infused-kim
#      revision: my-changes/oled-ext-pwr
#      import: app/west.yml
#  self:
#    path: config

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
